name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [lts/*]
    steps:
      - name: 🔀 Checkout Git Source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🚀 Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: 🔖 Release
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
